# Generated by Django 4.2.7 on 2023-12-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="bodybuilders",
            fields=[
                ("firstname", models.CharField(max_length=10)),
                ("lastname", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("FM", "Female"), ("ML", "Male")],
                        default="FM",
                        max_length=2,
                    ),
                ),
                ("height", models.PositiveSmallIntegerField()),
                ("weight", models.PositiveSmallIntegerField()),
                (
                    "nationalcode",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=15)),
                ("phonenumber", models.PositiveSmallIntegerField()),
                ("aim", models.TextField()),
                ("illness", models.TextField()),
                ("birthdate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="damages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_part", models.CharField(max_length=10)),
                ("what", models.CharField(max_length=100)),
                (
                    "when",
                    models.CharField(
                        choices=[("RM", " ماه های اخیر"), ("E", "قبلتر")],
                        default="E",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gyms",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("manager_name", models.CharField(max_length=20, unique=True)),
                ("manager_cv", models.TextField()),
                ("manager_password", models.CharField(max_length=15)),
                ("facilities", models.TextField()),
                ("capacity", models.PositiveSmallIntegerField()),
                ("numberofmachines", models.IntegerField()),
                ("foundationdate", models.DateField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="movements",
            fields=[
                (
                    "name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("machine_name", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finish_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="work_times",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("SHA", "Sanbe"),
                            ("1SH", "1shanbe"),
                            ("2SH", "2shanbe"),
                            ("3SH", "3shanbe"),
                            ("4SH", "4shanbe"),
                            ("5SH", "5shanbe"),
                            ("JOM", "Jomee"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "coach_crew",
                    models.CharField(
                        choices=[("CO", "coach"), ("CR", "crew")], max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="workers",
            fields=[
                (
                    "nationalcode",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("firstname", models.CharField(max_length=10)),
                ("lastname", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("FM", "Female"), ("ML", "Male")],
                        default="FM",
                        max_length=2,
                    ),
                ),
                ("password", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="coaches",
            fields=[
                (
                    "workers_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app1.workers",
                    ),
                ),
                ("sport_degree", models.TextField()),
                ("experience", models.TextField()),
            ],
            bases=("app1.workers",),
        ),
    ]
