# Generated by Django 4.2.7 on 2023-12-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="damages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_part", models.CharField(max_length=10)),
                ("what", models.CharField(max_length=100)),
                (
                    "when",
                    models.CharField(
                        choices=[("RM", " ماه های اخیر"), ("E", "قبلتر")],
                        default="E",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="work_times",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("SHA", "Sanbe"),
                            ("1SH", "1shanbe"),
                            ("2SH", "2shanbe"),
                            ("3SH", "3shanbe"),
                            ("4SH", "4shanbe"),
                            ("5SH", "5shanbe"),
                            ("JOM", "Jomee"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "coach_crew",
                    models.CharField(
                        choices=[("CO", "coach"), ("CR", "crew")], max_length=2
                    ),
                ),
            ],
        ),
    ]
