# Generated by Django 4.2.7 on 2023-12-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="damages", new_name="damage",),
        migrations.RenameModel(old_name="work_times", new_name="work_time",),
    ]
