# Generated by Django 4.2.7 on 2023-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager_customuser",
            name="manager_password",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="manager_customuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
