# Generated by Django 4.2.7 on 2023-12-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_manager_customuser_manager_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager_customuser",
            name="gym_name",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
