# Generated by Django 4.2.7 on 2023-12-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_alter_manager_customuser_gym_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="manager_customuser", name="gym_name",),
        migrations.RemoveField(
            model_name="manager_customuser", name="manager_password",
        ),
        migrations.AlterField(
            model_name="manager_customuser",
            name="email",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="manager_customuser",
            name="username",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
