# Generated by Django 4.2.7 on 2023-12-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_remove_manager_customuser_gym_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager_customuser",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
