# Generated by Django 4.2.7 on 2023-12-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_manager_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="gyms", name="phonenumber",),
        migrations.AddField(
            model_name="manager_customuser",
            name="phonenumber",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
